from day1 import day1
from day2 import day2
from day3 import day3

# day1.exercise1()
# print("")
# day1.exercise2()
# print("")
# day1.exercise3()
# print("")
# day1.exercise4()
# print("")
# day1.project()
# print("")
# day2.exercise1()
# print("")
# day2.exercise2()
# print("")
# day2.exercise3()
# print("")
# day2.project()
# print("")
# day3.even_or_odd()
# print("")
# day3.bmi_indicator()
# print("")
# day3.leapYear()
# print("")
# day3.pizzaChanllenge()
# print("")
day3.treasureIsland()
